# Default values for istio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

base:
  global:
    istioNamespace: smartscaler-demo-app

gateway:
  global:
    istioNamespace: smartscaler-demo-app
  service:
    # Type of service. Set to "None" to disable the service entirely
    type: ClusterIP
    ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443

istiod:
  global:
    istioNamespace: smartscaler-demo-app