# apiVersion: v1
# kind: Namespace
# metadata:
#   name: {{ .Values.base.global.istioNamespace }}
#   labels:
#     app.kubernetes.io/instance: {{ .Values.base.global.istioNamespace }}
#     app.kubernetes.io/name: {{ .Values.base.global.istioNamespace }}