{{- if and (not .Values.dataSources.datadog.existingSecret) .Values.dataSources.datadog.apiKey .Values.dataSources.datadog.appkey}}
apiVersion: v1
kind: Secret
metadata:
  name: datadog
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DD_API_KEY: {{ .Values.dataSources.datadog.apiKey | b64enc | quote }}
  DD_APP_KEY: {{ .Values.dataSources.datadog.appkey | b64enc | quote }}
{{- end }}
