agentConfiguration:
  host: https://gateway.saas1.smart-scaler.io
  clusterDisplayName: smart-scaler-agent
  # Do not change this
  clientID: tenant-apollo
  # Do not change this
  clientSecret: LS0tLS1CRUdJTiBQUklW # Replace with the valid one
inferenceAgent:
  inferenceAgentConfig:
    app:
      - metric_labels:
          app: "terraform-boutique"
          app_version: "1.0"
          customer: tenant-apollo
          kube_cluster_name: terraform-boutique-cluster
        metrics:
          - description: forwarded rps data from istio requests
            name: istio_requests_total_rate
            query: sum(rate(label_replace(istio_requests_total{namespace=~'demo', destination_workload=~'.*'},'kube_namespace', '$1', 'namespace', '(.*)')[2m:])) by (destination_service_name,response_code,destination_workload,source_workload,reporter,kube_namespace)
          - description: forwarded current number of pods
            name: current_pods
            query: sum by (kube_deployment,kube_namespace) (label_replace(label_replace(kube_deployment_spec_replicas{namespace=~'demo',deployment=~'.*'}, 'kube_deployment', '$1', 'deployment', '(.*)'),'kube_namespace', '$1', 'namespace', '(.*)'))
          - description: forwarded latency data from istio requests
            name: istio_request_duration_milliseconds_bucket_rate
            query: sum(irate(label_replace(istio_request_duration_milliseconds_bucket{namespace=~'demo',reporter=~'destination', destination_workload=~'.*'},'kube_namespace', '$1', 'namespace', '(.*)')[2m:])) by (le, response_code, destination_service_name, destination_workload, source_workload, reporter, kube_namespace)
          - description: forwarded cpu usage
            name: cpu_usage
            query: sum by (kube_deployment,kube_namespace) (label_replace(label_replace(rate(container_cpu_usage_seconds_total{namespace=~'demo',pod=~'.*'}[2m]),'kube_deployment','$1','pod','(.+)-(.+)-(.+)'),'kube_namespace', '$1', 'namespace', '(.*)'))
          - description: forwarded cpu requests
            name: cpu_requests
            query: sum by (kube_deployment,kube_namespace) (label_replace(label_replace(kube_pod_container_resource_requests{namespace=~'demo',container=~'.*[A-Za-z0-9].*|!POD',pod=~'.*',resource='cpu'},'kube_deployment','$1','pod','(.+)-(.+)-(.+)'),'kube_namespace','$1', 'namespace', '(.*)'))
          - description: forwarded memory usage
            name: memory_usage
            query: (avg (label_replace(label_replace(container_memory_working_set_bytes{namespace=~'demo',pod=~'.*'}, 'kube_deployment', '$1', 'pod', '(.*)-(.*)-(.*)'), 'kube_namespace', '$1','namespace', '(.*)')) by (kube_deployment,kube_namespace))
          - description: forwarded memory requests
            name: memory_requests
            query: sum by (kube_deployment,kube_namespace) (label_replace(label_replace(kube_pod_container_resource_requests{namespace=~'demo',container=~'.*[A-Za-z0-9].*|!POD',pod=~'.*',resource='memory'},'kube_deployment','$1','pod','(.+)-(.+)-(.+)'),'kube_namespace','$1', 'namespace', '(.*)'))
          - description: forwarded pods scheduled
            name: pods_scheduled
            query: sum by (kube_deployment,kube_namespace) (label_replace(label_replace(kube_deployment_spec_replicas{namespace=~'demo',deployment=~'.*'},'kube_deployment', '$1', 'deployment', '(.*)'),'kube_namespace', '$1', 'namespace','(.*)'))
        smart-scaler-enabled-services:
          - namespace: demo
            services:
              - adservice
              - cartservice
              - checkoutservice
              - currencyservice
              - emailservice
              - frontend
              - paymentservice
              - productcatalogservice
              - recommendationservice
              - redis-cart
              - shippingservice
    app_datasource:
      prometheus:
        url: "http://prometheus-server.monitoring.svc.cluster.local/"
    metric_interval: 60
    push_interval: 15
    slo: ""
