{{- if .Values.namedGitSecrets -}}
{{- range $namedGitSecret := .Values.namedGitSecrets }}
{{- if and ($namedGitSecret.name) ($namedGitSecret.gitUsername) ($namedGitSecret.gitPassword) ($namedGitSecret.url) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $namedGitSecret.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    agent.smart-scaler.io/secret-type: repository
type: Opaque
data:
  password: {{ $namedGitSecret.gitPassword | toString | b64enc }}
  type: Z2l0
  url: {{ $namedGitSecret.url | toString | b64enc }}
  username: {{ $namedGitSecret.gitUsername | toString | b64enc }}
{{- end }}
---
{{- end }}
{{- end }}