apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-agent
  labels:
    apps: inference-agent
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-agent
      version: v1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
      labels:
        app: inference-agent
        version: v1
    spec:
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: smart-scaler-config
            optional: true
      containers:
        - name: inference-agent
          image: '{{ .Values.inferenceAgent.image.repository }}:{{ .Values.inferenceAgent.image.tag }}'
          imagePullPolicy: {{ .Values.inferenceAgent.image.pullPolicy }}
          command: ["/venv/bin/python3"]
          args:
            [
              "inference-agent/metrics_agent.py",
              "--config",
              "/home/avesha/config/inference-agent-config.json",
            ]
          resources:
            requests:
              memory: 2Gi
              cpu: 500m
          env:
            - name: username_api
              valueFrom:
                secretKeyRef:
                  name: {{ template "smartscalerApi.secretName" . }}
                  key: username_api
                  optional: true
            - name: password_api
              valueFrom:
                secretKeyRef:
                  name: {{ template "smartscalerApi.secretName" . }}
                  key: password_api
                  optional: true
            - name: username_prom
              valueFrom:
                secretKeyRef:
                  name: {{ template "prometheus.secretName" . }}
                  key: username_prom
                  optional: true
            - name: password_prom
              valueFrom:
                secretKeyRef:
                  name: {{ template "prometheus.secretName" . }}
                  key: password_prom
                  optional: true
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "datadog.secretName" . }}
                  key: DD_API_KEY
                  optional: true
            - name: DD_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "datadog.secretName" . }}
                  key: DD_APP_KEY
                  optional: true

          volumeMounts:
            - name: config-volume
              mountPath: /home/avesha/config

      imagePullSecrets:
        - name: {{ .Values.imagePullSecretsName }}
