apiVersion: v1
kind: Service
metadata:
  name: inference-agent-service
spec:
  selector:
    app: inference-agent
    version: v1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
