{{- if and (not .Values.dataSources.prometheus.existingSecret) .Values.dataSources.prometheus.username .Values.dataSources.prometheus.password }}
apiVersion: v1
kind: Secret
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username_prom: {{ .Values.dataSources.prometheus.username | b64enc | quote }}
  password_prom: {{ .Values.dataSources.prometheus.password | b64enc | quote }}
{{- else }}
{{- range $namedDataSource := .Values.namedDataSources }}
  {{- if eq $namedDataSource.datasourceType "prometheus" }}
apiVersion: v1
kind: Secret
metadata:
  name: prometheus
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  {{- if and $namedDataSource.credentials.username $namedDataSource.credentials.password }}
  username_prom: {{ $namedDataSource.credentials.username | b64enc | quote }}
  password_prom: {{ $namedDataSource.credentials.password | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}