{{- if and (not .Values.smartscalerApi.existingSecret) .Values.smartscalerApi.username .Values.smartscalerApi.password }}
apiVersion: v1
kind: Secret
metadata:
  name: smartscaler-api
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username_api: {{ .Values.smartscalerApi.username | b64enc | quote }}
  password_api: {{ .Values.smartscalerApi.password | b64enc | quote }}
{{- end }}

  