
autoscaling:
  enabled: false
# Example deployment override values file for nginx
smartscaler:
  enabled: true
  minReplicas: 1 # Resetting values after end of event: scale-pod
  maxReplicas: 60 # Updating for event: scale-pod
  trigger:
    type: prometheus
    metadata:
      serverAddress: https://metricsgateway.2f396c0d.saas-sandbox.smart-scaler.io/
      metricName: smartscaler_hpa_num_pods
      query: smartscaler_hpa_num_pods{ss_deployment_name="nginx", ss_namespace="app1", ss_cluster_name="smart-scaler-agent-thescore"}
      threshold: "1"
