# Please have either autoscaling or smartscaler enabled as true and not both enabled as true
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
# Example deployment override values file for nginx
smartscaler:
  enabled: false
  minReplicas: 1 
  maxReplicas: 10 
