autoscaling:
  enabled: true
# Example deployment override values file for nginx
smartscaler:
  enabled: false
  minReplicas: 1 # Resetting values after end of event: app1
  maxReplicas: 10 # Updating for event: app1
  trigger:
    type: datadog
    metadata:
      # Prometheus
      # serverAddress: https://metricsgateway.2f396c0d.saas-sandbox.smart-scaler.io/
      # metricName: smartscaler_hpa_num_pods
      # query: smartscaler_hpa_num_pods{ss_cluster_name="erics-gcp-cluster", ss_deployment_name="cartservice", ss_namespace="demo"}
      # threshold: "1"
      # Datadog
      serverAddress: "http://inference-agent-service.smart-scaler.svc.cluster.local:8080/metrics"
      metricName: smartscaler_hpa_num_pods
      query: smartscaler_hpa_num_pods{ss_cluster_name="smart-scaler-prod-demoapp-cluster", ss_deployment_name="app1", ss_namespace="app1"}
      threshold: "1"
