# Example deployment override values file for nginx
smartscaler:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  trigger:
    type: prometheus
    metadata:
      serverAddress: https://metricsgateway.apollo.saas.smart-scaler.io/
      metricName: hpa_num_pods
      query: hpa_num_pods{job="smartscaler_nginx_app1_tutorial-agent"}
      threshold: "1"
