apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
spec:
  project: smartscaler-tutorials
  destination:
    server: "https://34.134.95.101"
    namespace: "app1"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
  sources:
    - repoURL: https://github.com/smart-scaler/smartscaler-tutorials.git
      targetRevision: HEAD
      path: "charts/app1/"
      helm:
        # Release name override (defaults to application name)
        releaseName: "app1"
        valueFiles:
        - "../../charts/app1/values.yaml"
        - "../../charts/app1/values-override.yaml"
