apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: "smartscaler-tutorials"
  source:
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.13.1
    chart: keda
  destination:
    name: "https://34.134.95.101"
    namespace: "keda"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 2
