apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom
  namespace: monitoring
spec:
  project: smartscaler-tutorials
  destination:
    server: "https://34.134.95.101"
    namespace: "monitoring"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 2
  sources:
    - repoURL: https://github.com/smart-scaler/smartscaler-tutorials.git
      targetRevision: HEAD
      path: "charts/kube-prometheus-stack/"
      helm:
        # Release name override (defaults to application name)
        releaseName: "kube-prom"
