agentConfiguration:
  clientID: tenant-apollo

namedDataSources:
  - name: prometheus
    datasourceType: prometheus
    url: "http://10.100.248.141:9090"

namedGitSecrets:
  - name: git-access-secret
    gitUsername: wmariuss # Username
    gitPassword: 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 # PAT token
    url: https://github.com/smart-scaler/smartscaler-tutorials.git # URL of the git repository

configGenerator:
  apps:
    # This is an example and needs to be removed
    - app: app1
      app_version: "1.0"
      namedDatasource: prometheus
      aggregation_interval: 60 # optional
      scape_interval: 15 # optional
      gitConfig:
        branch: "marius/app-demo-thescore" # branch of the git repo
        repository: https://github.com/smart-scaler/smartscaler-tutorials.git # url of the git repo
        secretRef: git-access-secret
      clusters:
        - name: smart-scaler-prod-demoapp-cluster # name of the cluster
          namespaces:
            - name: app1 # name of the namespace
              metricsType: istio
              deployments: # list of the deployments
                - name: nginx # name of the deployment
                  eventConfig: # configurations for event auto-scaling
                    gitPath: "charts/app1/values-override.yaml"
                # - name: cart # name of the deployment
                #   eventConfig: # configurations for event auto-scaling
                #     gitPath: "edge/sandbox/values-edge-us-west-2.yaml"
                #     gitConfig:
                #       branch: "main" # branch of the git repo
                #       repository: https://sandbox-argocd.git # url of the git repo
                #       secretRef: git-access-secret
