agentConfiguration:
  clientID: tenant-apollo

namedDataSources:
  - name: "datadog"
    datasourceType: "datadog"
    url: "https://api.us5.datadoghq.com"
    credentials:
      apiKey: "9cfe4744110c27d301dc885c9de05d2f"
      appKey: "229ec69b1e2628f109862fb35eefd1020f43a375"

namedGitSecrets:
  - name: git-access-secret
    gitUsername: wmariuss # Username
    gitPassword: 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 # PAT token
    url: https://github.com/smart-scaler/smartscaler-tutorials.git # URL of the git repository

configGenerator:
  apps:
    # This is an example and needs to be removed
    - app: acmefitness
      app_version: "1.0"
      namedDatasource: datadog
      aggregation_interval: 60 # optional
      scape_interval: 15 # optional
      gitConfig:
        branch: "marius/app-demo-thescore" # branch of the git repo
        repository: https://github.com/smart-scaler/smartscaler-tutorials.git # url of the git repo
        secretRef: git-access-secret
      clusters:
        - name: acme-demo-cluster # name of the cluster
          namespaces:
            - name: acmefitness # name of the namespace
              metricsType: istio
              deployments: # list of the deployments
                - name: frontend # name of the deployment
                  eventConfig: # configurations for event auto-scaling
                    gitPath: "charts/app1/values-override.yaml"
                - name: catalog # name of the deployment
                  eventConfig: # configurations for event auto-scaling
                    gitPath: "charts/app1/values-override.yaml"
                    gitConfig:
                      branch: "marius/app-demo-thescore" # branch of the git repo
                      repository: https://github.com/smart-scaler/smartscaler-tutorials.git # url of the git repo
                      secretRef: git-access-secret
