# Add these 2 sections in the keda application template
apiVersion: v1
kind: Secret
metadata:
  name: keda-prom-secret
  namespace: keda
data:
  # Enter the vault path for smartscalermetrics
  username: tenant-apollo-metricsgw-user 
  password: O3CNeUaRZhpW0
---
apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: keda-prom-creds
  namespace: keda
spec:
  secretTargetRef:
    - parameter: username
      name: keda-prom-secret
      key: username
    - parameter: password
      name: keda-prom-secret
      key: password
