# Add these 2 sections in the keda application template
apiVersion: v1
kind: Secret
metadata:
  name: keda-prom-secret
  namespace: keda
data:
  # Enter the vault path for smartscalermetrics (base64 encoded)
  username: dGVuYW50LWFwb2xsby1tZXRyaWNzZ3ctdXNlcg==
  password: UUlGSTY0dzc2OFkxcQ==
---
apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: keda-prom-creds
  namespace: keda
spec:
  secretTargetRef:
    - parameter: username
      name: keda-prom-secret
      key: username
    - parameter: password
      name: keda-prom-secret
      key: password