inferenceAgentConfig:
  app:
  - metric_labels:
      app: app1
      app_version: "1.0"
      customer: tenant-apollo
      kube_cluster_name: smart-scaler-agent-thescore
    metrics:
    - description: forwarded rps data from istio requests
      name: istio_requests_total_rate
      query: sum(rate(label_replace(istio_requests_total{namespace=~'app1', destination_workload=~'.*(nginx).*'},'kube_namespace',
        '$1', 'namespace', '(.*)')[1m:])) by (destination_service_name,response_code,destination_workload,source_workload,reporter,kube_namespace)
    - description: forwarded current number of pods
      name: current_pods
      query: sum by (kube_deployment,kube_namespace) (label_replace(label_replace(kube_deployment_spec_replicas{namespace=~'app1',deployment=~'.*(nginx).*'},
        'kube_deployment', '$1', 'deployment', '(.*)'),'kube_namespace', '$1', 'namespace',
        '(.*)'))
    - description: forwarded latency data from istio requests
      name: istio_request_duration_milliseconds_bucket_rate
      query: sum(irate(label_replace(istio_request_duration_milliseconds_bucket{namespace=~'app1',reporter=~'destination',
        destination_workload=~'.*(nginx).*'},'kube_namespace', '$1', 'namespace',
        '(.*)')[1m:])) by (le, response_code, destination_service_name, destination_workload,
        source_workload, reporter, kube_namespace)
    - description: forwarded cpu usage
      name: cpu_usage
      query: sum by (kube_deployment,kube_namespace) (label_replace(label_replace(rate(container_cpu_usage_seconds_total{namespace=~'app1',pod=~'.*(nginx).*'}[1m]),'kube_deployment','$1','pod','(.+)-(.+)-(.+)'),'kube_namespace',
        '$1', 'namespace', '(.*)'))*(10^9)
    - description: forwarded cpu requests
      name: cpu_requests
      query: sum by (kube_deployment,kube_namespace) (label_replace(label_replace(kube_pod_container_resource_requests{namespace=~'app1',container=~'.*[A-Za-z0-9].*|!POD',pod=~'.*(nginx).*',resource='cpu'},'kube_deployment','$1','pod','(.+)-(.+)-(.+)'),'kube_namespace',
        '$1', 'namespace', '(.*)'))
    - description: forwarded memory usage
      name: memory_usage
      query: (avg (label_replace(label_replace(container_memory_working_set_bytes{namespace=~'app1',pod=~'.*(nginx).*'},
        'kube_deployment', '$1', 'pod', '(.*)-(.*)-(.*)'), 'kube_namespace', '$1',
        'namespace', '(.*)')) by (kube_deployment,kube_namespace))
    - description: forwarded memory requests
      name: memory_requests
      query: sum by (kube_deployment,kube_namespace) (label_replace(label_replace(kube_pod_container_resource_requests{namespace=~'app1',container=~'.*[A-Za-z0-9].*|!POD',pod=~'.*(nginx).*',resource='memory'},'kube_deployment','$1','pod','(.+)-(.+)-(.+)'),'kube_namespace',
        '$1', 'namespace', '(.*)'))
    - description: forwarded pods scheduled
      name: pods_scheduled
      query: sum by (kube_deployment,kube_namespace) (label_replace(label_replace(kube_deployment_spec_replicas{namespace=~'app1',deployment=~'.*(nginx).*'},
        'kube_deployment', '$1', 'deployment', '(.*)'),'kube_namespace', '$1', 'namespace',
        '(.*)'))
    smart-scaler-enabled-services:
    - namespace: app1
      services:
      - nginx
  app_datasource:
    prometheus:
      url: http://10.100.248.141:9090
  metric_interval: 60
  push_interval: 15
  smartscaler_api:
    url: https://apigateway-apollo.saas1.smart-scaler.io
  smartscaler_job_name: app1-smart-scaler-agent
  