{{- $ca := genCA "agent-controller-webhook-service" 3650 -}}
{{- $cn := printf "agent-controller-webhook-service" -}}
{{- $altName1 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc.cluster.local" $cn .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca -}}

apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-cert
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  tls.key: {{ $cert.Key | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}

---

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: agent-controller
    app.kubernetes.io/instance: mutating-webhook-configuration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mutatingwebhookconfiguration
    app.kubernetes.io/part-of: agent-controller
  name: agent-controller-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ $ca.Cert | b64enc }}
    service:
      name: agent-controller-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-agent-smart-scaler-io-v1alpha1-applicationconfig
  failurePolicy: Fail
  name: mapplicationconfig.kb.io
  rules:
  - apiGroups:
    - agent.smart-scaler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applicationconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ $ca.Cert | b64enc }}
    service:
      name: agent-controller-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-agent-smart-scaler-io-v1alpha1-eventconfig
  failurePolicy: Fail
  name: meventconfig.kb.io
  rules:
  - apiGroups:
    - agent.smart-scaler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - eventconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ $ca.Cert | b64enc }}
    service:
      name: agent-controller-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-agent-smart-scaler-io-v1alpha1-eventconfigset
  failurePolicy: Fail
  name: meventconfigset.kb.io
  rules:
  - apiGroups:
    - agent.smart-scaler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - eventconfigsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ $ca.Cert | b64enc }}
    service:
      name: agent-controller-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-agent-smart-scaler-io-v1alpha1-scalingratioconfig
  failurePolicy: Fail
  name: mscalingratioconfig.kb.io
  rules:
  - apiGroups:
    - agent.smart-scaler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scalingratioconfigs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: agent-controller
    app.kubernetes.io/instance: validating-webhook-configuration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: validatingwebhookconfiguration
    app.kubernetes.io/part-of: agent-controller
  name: agent-controller-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ $ca.Cert | b64enc }}
    service:
      name: agent-controller-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-agent-smart-scaler-io-v1alpha1-applicationconfig
  failurePolicy: Fail
  name: vapplicationconfig.kb.io
  rules:
  - apiGroups:
    - agent.smart-scaler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - applicationconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ $ca.Cert | b64enc }}
    service:
      name: agent-controller-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-agent-smart-scaler-io-v1alpha1-eventconfig
  failurePolicy: Fail
  name: veventconfig.kb.io
  rules:
  - apiGroups:
    - agent.smart-scaler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - eventconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ $ca.Cert | b64enc }}
    service:
      name: agent-controller-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-agent-smart-scaler-io-v1alpha1-eventconfigset
  failurePolicy: Fail
  name: veventconfigset.kb.io
  rules:
  - apiGroups:
    - agent.smart-scaler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - eventconfigsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ $ca.Cert | b64enc }}
    service:
      name: agent-controller-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-agent-smart-scaler-io-v1alpha1-scalingratioconfig
  failurePolicy: Fail
  name: vscalingratioconfig.kb.io
  rules:
  - apiGroups:
    - agent.smart-scaler.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - scalingratioconfigs
  sideEffects: None
