apiVersion: v1
kind: Secret
metadata:
  name: smart-scaler-agent-api-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # Client ID is plain text, therefore it must be base64 encoded
  clientId: {{ required "A valid value is required!" .Values.agentConfiguration.clientID | b64enc | quote }}
  # Client Secret is already base64 encoded
  clientSecret: {{ required "A valid value is required!" .Values.agentConfiguration.clientSecret | quote }}
