{{- if hasKey .Values "smartscalerMetrics" }}
{{- if and (not .Values.smartscalerMetrics.existingSecret) .Values.smartscalerMetrics.username .Values.smartscalerMetrics.password }}
apiVersion: v1
kind: Secret
metadata:
  name: keda-prom-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.smartscalerMetrics.username | b64enc | quote }}
  password: {{ .Values.smartscalerMetrics.password | b64enc | quote }}
---
{{- end }}
{{- end }}